name: Dredd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    timeout-minutes: 1
    container: pbui/cse-30341-fa20-assignments
    steps:
    - uses: actions/checkout@v2

    - name: Testing
      run:  make BRANCH=${GITHUB_HEAD_REF} test
